"use client";

import { useActionState, useState } from "react";
import { createLogo, deleteLogo, moveLogo, updateLogo, type ActionResult } from "../../../lib/admin/actions";
import type { LogoRecord } from "../../../lib/content/types";
import { ActionMessage } from "../components/action-message";
import { AssetUploadForm } from "../components/asset-upload-form";
import { SubmitButton } from "../components/submit-button";

const initialState: ActionResult | null = null;
const inputClass = "w-full rounded-xl border border-black/10 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#83c94d]";

export function AddLogoForm() {
  const [state, formAction] = useActionState(createLogo, initialState);
  const [preview, setPreview] = useState<string | null>(null);
  return <details className="mb-6 rounded-2xl border border-[#83c94d]/40 bg-white p-5"><summary className="cursor-pointer font-bold text-[#315317]">Add Logo</summary><form action={formAction} className="mt-5 grid gap-4 md:grid-cols-2"><label className="block"><span className="mb-1.5 block text-sm font-semibold">Company or organization name</span><input name="name" required className={inputClass} /></label><label className="block"><span className="mb-1.5 block text-sm font-semibold">Logo group</span><select name="logo_type" required defaultValue="partner" className={inputClass}><option value="main">Main</option><option value="partner">Partner</option><option value="client">Client</option></select></label><label className="block md:col-span-2"><span className="mb-1.5 block text-sm font-semibold">Logo image</span><input name="file" type="file" required accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file=event.target.files?.[0]; if (!file) return setPreview(null); if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) { event.currentTarget.value=""; return setPreview(null); } setPreview(URL.createObjectURL(file)); }} className="block w-full text-sm text-zinc-600 file:mr-3 file:rounded-lg file:border-0 file:bg-[#e6f8c9] file:px-3 file:py-2 file:font-semibold" />{preview ? <img src={preview} alt="Selected logo preview" className="mt-3 h-28 w-full rounded-xl bg-[#f5f7f3] object-contain p-3" /> : null}<span className="mt-1 block text-xs text-zinc-500">JPEG, PNG, or WebP, up to 5 MB.</span></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="is_visible" defaultChecked /> Visible on website</label><div className="md:col-span-2"><ActionMessage result={state} reset={() => undefined} /><SubmitButton label="Add logo" /></div></form></details>;
}

export function LogoCard({ logo, position, total }: { logo: LogoRecord; position: number; total: number }) {
  const [state, formAction] = useActionState(updateLogo, initialState);
  const [moveState, moveAction] = useActionState(moveLogo, initialState);
  const [deleteState, deleteAction] = useActionState(deleteLogo, initialState);
  return <article className="rounded-2xl border border-black/5 bg-white p-4"><div className="mb-4 flex h-32 items-center justify-center rounded-xl bg-[#f5f7f3] p-5"><img src={logo.image?.public_url} alt={`${logo.name} logo`} className="max-h-full w-full object-contain" /></div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#4a7b1d]">{logo.logo_type} · {position}</p><form action={formAction} className="mt-3 space-y-3"><input type="hidden" name="id" value={logo.id} /><label className="block"><span className="mb-1 block text-sm font-semibold">Name</span><input name="name" required defaultValue={logo.name} className={inputClass} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="is_visible" defaultChecked={logo.is_visible} /> Visible on website</label><ActionMessage result={state} reset={() => undefined} /><SubmitButton label="Save logo" /></form><AssetUploadForm assetId={logo.storage_asset_id} assetType="logo" /><div className="mt-4 flex flex-wrap gap-2 border-t border-black/5 pt-4"><form action={moveAction}><input type="hidden" name="id" value={logo.id} /><input type="hidden" name="direction" value="up" /><button type="submit" disabled={position === 1} className="rounded-lg border border-black/10 px-3 py-2 text-sm font-semibold disabled:opacity-40">Move Up</button></form><form action={moveAction}><input type="hidden" name="id" value={logo.id} /><input type="hidden" name="direction" value="down" /><button type="submit" disabled={position === total} className="rounded-lg border border-black/10 px-3 py-2 text-sm font-semibold disabled:opacity-40">Move Down</button></form><form action={deleteAction} onSubmit={(event) => { if (!window.confirm(`Delete ${logo.name}? This cannot be undone.`)) event.preventDefault(); }}><input type="hidden" name="id" value={logo.id} /><button type="submit" className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Delete</button></form></div><ActionMessage result={moveState ?? deleteState} reset={() => undefined} /></article>;
}